# Generated by Django 3.1.2 on 2020-10-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
